site:
  title: TideFinder Plugin Documentation

content:
  sources:
  - url: ../
    branches: HEAD
    start_path: docs/

ui:
  output_dir: assets
  bundle:
    url: https://github.com/Rasbats/TF/files/6096963/ui-bundle.zip
    snapshot: true
    

output:
  clean: true
  

asciidoc:
  attributes:
    idprefix: ''
    idseparator: '-'
